### ISSUE TITLE
:up: for upgrading dependencies and/or bumping up versions

### ISSUE THREAD

**Issue by lukaszklis** [robinpokorny/git3moji#7]
I’d like to have a clear division between features I develop and dependencies upgrades I do in the projects I manage. WDYT about using ”:up:” for it?

**Comment by lukaszklis** [comment]
`:up:` would be an alternative, however it’s not a 3-letters emoji. ;)

**Comment by robinpokorny** [comment]
Although I understand what you mean, I disagree that this case should be separated.

Use of `:up:` falls into one of three cases:
1. _Dependencies upgrade_: I strongly believe these should use `:zap:` or `:bug:` as it directly changes the app functionality (why else would you update). 

2. _Dev Dependency upgrade_: Here, I'd say it should be `:tv:` as it mostly means a change in tooling. Or it can be `:cop:` if connected to testing or code format. I can imagine this may be `:bug:` (e.g. a fix in webpack or babel plugin update) or a feature for the same reasons.

3. _Release_: (Do you suggest it, right?) This is an interesting question. I generally assumed this could be `:zap:` or – maybe better – `:abc:` since this translates to describing the code and not changing it.

Lastly, one of the core ideas of git3moji – that differs it from gitmoji – is the limited pool of emojis to choose from. Adding new emojis for these narrow use cases is a slippery slope, it is difficult to stop once you start. This does not feel important enough.

As a supporting reference, [Angular convention](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type) does not cover this case separately either.

**Comment by lukaszklis** [comment]
Thanks for elaborating on the topic, I read your comment and I agree with the first and second statement.

As it comes to the third one, I actually didn’t mean it when opening the issue, however it could be an option to consider.
